# Generated by Django 4.2.7 on 2024-03-23 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_ordermodel'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='ordermodel',
            table='tb_order',
        ),
    ]
