# Generated by Django 4.2.7 on 2024-03-25 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_ordermodel_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='u',
            field=models.ForeignKey(db_column='u_id', on_delete=django.db.models.deletion.CASCADE, to='user.usermodel'),
        ),
        migrations.RenameField(
            model_name='ordermodel',
            old_name='u',
            new_name='u_id',
        ),
    ]
